"""
Footer Component for HTML Report.

Generates the report footer with version and timestamp information.
"""

from typing import Dict, Any
from ..base_component import BaseComponent


class FooterComponent(BaseComponent):
    """Component for generating report footer."""

    def render(self, summary: Dict[str, Any]) -> str:
        """
        Render report footer with version and timestamp.

        Args:
            summary: Summary statistics dictionary

        Returns:
            HTML string for footer section
        """
        timestamp = summary.get("scan_timestamp", "Unknown")
        return f"""
        <footer class="report-footer">
            <p>Generated by <strong>vscan</strong> v{self.version} on {self._safe_escape(timestamp)}</p>
            <p>For more information, visit <a href="https://vscan.dev" target="_blank">vscan.dev</a></p>
        </footer>
        """
