name: Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: [bug, P2-medium, complexity/M]
assignees:
  - jvlivonius

body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report

        Thank you for reporting a bug! Please provide detailed information to help us reproduce and fix the issue.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Brief one-sentence description of the bug
      placeholder: "vscan crashes when scanning extension with special characters in name"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear and concise description of what the bug is
      placeholder: |
        When scanning an extension with special characters in the name,
        vscan throws an UnicodeEncodeError and crashes instead of handling
        the error gracefully.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Run command: `vscan scan --publisher microsoft`
        2. Wait for extension "Test™-Extension" to be scanned
        3. Observe crash with stack trace
      value: |
        1. Run command: `vscan scan ...`
        2. Observe error: ...
        3. Expected result was: ...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: |
        The extension name should be properly sanitized and the scan should
        complete successfully with results displayed or an appropriate error
        message shown.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened (include error messages, stack traces)
      placeholder: |
        ```
        Traceback (most recent call last):
          File "vscode_scanner/scanner.py", line 145, in scan_extension
            print(extension_name)
        UnicodeEncodeError: 'ascii' codec can't encode character '\u2122'
        ```
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Bug Severity
      description: How severe is this bug?
      options:
        - P0-critical (blocks all usage, data loss)
        - P1-high (major functionality broken)
        - P2-medium (feature partially broken)
        - P3-low (minor issue, workaround available)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: System information
      placeholder: |
        - **OS:** macOS 14.0 / Ubuntu 22.04 / Windows 11
        - **Python version:** 3.11.5 (run `python3 --version`)
        - **vscan version:** 3.7.2 (run `vscan --version`)
        - **Installation method:** pip / pipx / source
      value: |
        - **OS:**
        - **Python version:**
        - **vscan version:**
        - **Installation method:**
    validations:
      required: true

  - type: input
    id: parent-issue
    attributes:
      label: Parent Issue (if applicable)
      description: Is this bug part of a larger feature or epic?
      placeholder: "#142 or leave empty"
    validations:
      required: false

  - type: input
    id: milestone
    attributes:
      label: Milestone
      description: Target version for fix
      placeholder: "v3.7.3"
    validations:
      required: false

  - type: input
    id: required-docs
    attributes:
      label: Required Documentation
      description: Comma-separated list of documentation files to read before fixing
      placeholder: "ARCHITECTURE.md, ERROR_HANDLING.md, SECURITY.md"
      value: "ARCHITECTURE.md, ERROR_HANDLING.md"
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: |
        List dependencies:
        - **Blocked By**: Issues that must be fixed first
        - **Blocks**: Issues blocked by this bug
        - **Related**: Related bugs or issues
      placeholder: |
        Blocked By: #140
        Blocks: #145
        Related: #150
      value: |
        Blocked By: None
        Blocks: None
        Related: None
    validations:
      required: false

  - type: dropdown
    id: security-impact
    attributes:
      label: Security Impact
      description: Does this bug have security implications?
      options:
        - "No security impact"
        - "Information disclosure (error messages leak paths)"
        - "Input validation bypass"
        - "Authentication/Authorization issue"
        - "Potential code injection"
        - "Other security concern"
    validations:
      required: true

  - type: dropdown
    id: layer
    attributes:
      label: Architecture Layer Affected
      description: Which layer of the 3-layer architecture is affected?
      options:
        - Presentation (CLI, HTML reports, display)
        - Application (Scanner, business logic)
        - Infrastructure (API, cache, file operations)
        - Multiple layers
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and Stack Traces
      description: Paste relevant log output, stack traces, or error messages
      placeholder: |
        ```
        # Paste logs here
        ```
      render: shell
    validations:
      required: false

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: If you've found a temporary workaround, share it to help others
      placeholder: |
        Setting `PYTHONIOENCODING=utf-8` before running vscan prevents the crash.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Fix Requirements

        Specify what needs to be fixed and how to verify the fix.

  - type: textarea
    id: root-cause
    attributes:
      label: Root Cause (if known)
      description: Analysis of why this bug occurs
      placeholder: |
        The issue occurs in scanner.py:145 where extension names are printed
        without proper encoding handling. The code doesn't use sanitize_string()
        utility which would handle special characters properly.
    validations:
      required: false

  - type: textarea
    id: proposed-fix
    attributes:
      label: Proposed Fix
      description: How should this bug be fixed?
      placeholder: |
        **Files to Modify:**
        - vscode_scanner/scanner.py - Use sanitize_string() for extension names
        - vscode_scanner/utils.py - Ensure sanitize_string() handles unicode

        **Functions to Modify:**
        - scanner.py:scan_extension() - Apply sanitization before output

        **Tests to Add:**
        - tests/test_scanner.py::test_special_chars_in_extension_name()
        - tests/test_regression.py::test_unicode_handling()
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Acceptance Criteria

        The bug is fixed when all items are checked:

  - type: checkboxes
    id: acceptance-criteria
    attributes:
      label: Fix Completion Checklist
      options:
        - label: Bug reproduced with test case
        - label: Root cause identified and documented
        - label: Fix implemented following documented patterns
        - label: Regression test added to prevent recurrence
        - label: Security validation applied (validate_path(), sanitize_string())
        - label: No new bugs or regressions introduced
        - label: All existing tests still pass
        - label: Pre-commit hooks pass (bandit, pip-audit, black, isort)
        - label: Manual verification completed with original reproduction steps
        - label: Documentation updated if behavior changed

  - type: checkboxes
    id: security-requirements
    attributes:
      label: Security Requirements (if applicable)
      options:
        - label: validate_path() used for all file operations
        - label: sanitize_string() used for all user input
        - label: No path disclosure in error messages
        - label: Security impact assessed and documented

  - type: checkboxes
    id: architecture-requirements
    attributes:
      label: Architecture Requirements (if applicable)
      options:
        - label: Fix respects layer boundaries (P → A → I, one-way only)
        - label: Follows existing error handling patterns
        - label: No infrastructure imports in presentation layer

  - type: markdown
    attributes:
      value: |
        ## Agent Implementation

        **Agent-Ready Criteria:**
        - Bug can be reproduced consistently
        - Root cause understood (or hypothesis formed)
        - Required documentation listed above
        - Acceptance criteria clearly defined
        - Security impact assessed

        **To trigger automated fix implementation:**
        ```bash
        /gh:implement-issue #<issue-number>
        ```

  - type: textarea
    id: verification-steps
    attributes:
      label: Manual Verification Steps
      description: How to verify the bug is fixed
      placeholder: |
        1. Run original reproduction command: vscan scan --publisher microsoft
        2. Verify extension with special characters scans successfully
        3. Check logs for proper sanitization
        4. Confirm no error messages or crashes
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: |
        - Screenshots if applicable
        - Extension list if relevant to scan results
        - Related GitHub issues or discussions
        - Performance impact if applicable
    validations:
      required: false
