name: Refactoring
description: Code refactoring for improved maintainability, testability, or performance
title: "[REFACTOR] "
labels: [refactoring, technical-debt, P2-medium]
assignees:
  - jvlivonius

body:
  - type: markdown
    attributes:
      value: |
        ## Code Refactoring

        Use this template for:
        - Improving code structure and maintainability
        - Extracting patterns for better testability
        - Removing technical debt
        - Performance optimizations
        - Architectural improvements

        **NOT for new features!** Use Feature template for new functionality.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Brief one-sentence description of the refactoring
      placeholder: "Extract ProgressCallback pattern for testability"
    validations:
      required: true

  - type: dropdown
    id: refactoring-motivation
    attributes:
      label: Refactoring Motivation
      description: Primary reason for this refactoring
      options:
        - "Testability (improve test coverage or test quality)"
        - "Maintainability (simplify code, reduce complexity)"
        - "Performance (optimize speed or resource usage)"
        - "Technical Debt (address anti-patterns or code smells)"
        - "Architecture (improve separation of concerns, layer boundaries)"
        - "Security (eliminate security anti-patterns)"
    validations:
      required: true

  - type: textarea
    id: current-problem
    attributes:
      label: Current Problem
      description: What makes the current implementation problematic?
      placeholder: |
        **Current State:**
        Scanner class has tightly-coupled console output via Rich library,
        making it impossible to test without mocking the entire Rich console.

        **Problems:**
        - Tests are brittle due to Rich console mocking
        - Can't verify scan behavior without display side effects
        - Difficult to test progress reporting logic
        - Scanner class violates Single Responsibility Principle

        **Technical Debt:**
        - Test coverage: scanner.py only 72% (below 80% target)
        - Cyclomatic complexity: scan_extension() = 15 (target: <10)
        - Code smell: Mixed concerns (business logic + presentation)
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How should the code be refactored?
      placeholder: |
        **Refactoring Approach:**
        Extract ProgressCallback protocol/interface to decouple scanner from console output.

        **New Structure:**
        1. Define ProgressCallback protocol (Application layer)
        2. Implement RichProgressCallback (Presentation layer)
        3. Inject callback into Scanner via constructor
        4. Tests can use MockProgressCallback

        **Files to Modify:**
        - vscode_scanner/scanner.py - Remove direct Rich calls, use callback
        - vscode_scanner/types.py - Add ProgressCallback protocol
        - vscode_scanner/cli.py - Inject RichProgressCallback
        - vscode_scanner/display.py - Implement RichProgressCallback

        **Files to Create:**
        - tests/mocks.py - Add MockProgressCallback for testing

        **Example Pattern:**
        ```python
        # Before:
        class Scanner:
            def scan(self):
                console.print("[green]Scanning...")

        # After:
        class Scanner:
            def __init__(self, progress_callback: ProgressCallback):
                self.progress = progress_callback

            def scan(self):
                self.progress.report("Scanning...")
        ```
    validations:
      required: true

  - type: dropdown
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: Will this refactoring break existing APIs?
      options:
        - "No - Internal refactoring only"
        - "Yes - Public API changes (requires major version)"
        - "Minimal - Deprecation path provided"
    validations:
      required: true

  - type: textarea
    id: impact-analysis
    attributes:
      label: Impact Analysis
      description: What will be affected by this refactoring?
      placeholder: |
        **Modules Affected:**
        - vscode_scanner/scanner.py (major changes)
        - vscode_scanner/cli.py (minor changes - inject callback)
        - vscode_scanner/display.py (new callback implementation)
        - tests/test_scanner.py (update all tests to use mock callback)

        **Public API Impact:**
        - CLI commands: No change (transparent to users)
        - Library usage: Internal Scanner API changes (not public)
        - Configuration: No changes needed

        **Test Impact:**
        - 15 tests need updating to use MockProgressCallback
        - Expected test coverage increase: 72% → 85%
        - Existing behavior preserved (verified by tests)

        **Dependencies:**
        - No new external dependencies
        - No changes to Rich library usage (moved to display layer)

        **Performance Impact:**
        - Negligible (callback overhead < 1ms per call)
        - May improve performance by reducing console I/O during testing
    validations:
      required: true

  - type: textarea
    id: migration-path
    attributes:
      label: Migration Path (if breaking)
      description: How will users migrate to refactored code?
      placeholder: |
        **For Library Users (if applicable):**
        1. Old API deprecated in v3.8.0 with warnings
        2. New API available alongside old API
        3. Migration guide in docs/guides/MIGRATION_v3.8.md
        4. Old API removed in v4.0.0

        **Deprecation Warnings:**
        ```python
        @deprecated("Use Scanner(progress_callback=...) instead")
        def old_scan_method():
            ...
        ```
    validations:
      required: false

  - type: input
    id: milestone
    attributes:
      label: Milestone
      description: Target version for this refactoring
      placeholder: "v3.7.0"
    validations:
      required: false

  - type: input
    id: required-docs
    attributes:
      label: Required Documentation
      description: Comma-separated list of docs to read before refactoring
      placeholder: "ARCHITECTURE.md, TESTING.md, PRD.md"
      value: "ARCHITECTURE.md, TESTING.md"
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: |
        List dependencies:
        - **Blocked By**: Issues that must be completed first
        - **Blocks**: Issues that depend on this refactoring
        - **Related**: Related refactoring or tech debt issues
      placeholder: |
        Blocked By: None
        Blocks: #160 (comprehensive scanner tests)
        Related: #155 (extract cache interface)
      value: |
        Blocked By: None
        Blocks: None
        Related: None
    validations:
      required: false

  - type: dropdown
    id: layer
    attributes:
      label: Primary Architecture Layer
      description: Which layer is most affected?
      options:
        - Presentation (CLI, HTML reports, display)
        - Application (Scanner, business logic)
        - Infrastructure (API, cache, file operations)
        - Cross-cutting (affects multiple layers)
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Acceptance Criteria

        Refactoring is complete when all items are checked:

  - type: checkboxes
    id: acceptance-criteria
    attributes:
      label: Completion Checklist
      options:
        - label: Code refactored following ARCHITECTURE.md patterns
        - label: All existing tests updated and passing
        - label: No behavior changes (verified by tests)
        - label: Test coverage maintained or improved
        - label: Code complexity reduced (lower cyclomatic complexity)
        - label: Architecture tests pass (layer boundaries respected)
        - label: Security tests pass (no new vulnerabilities)
        - label: Pre-commit hooks pass (linting, formatting)
        - label: Documentation updated to reflect new structure
        - label: Migration guide created (if breaking changes)

  - type: checkboxes
    id: quality-improvements
    attributes:
      label: Quality Improvements
      options:
        - label: Cyclomatic complexity reduced
        - label: Code duplication eliminated
        - label: Single Responsibility Principle followed
        - label: Dependency injection used appropriately
        - label: Testability improved
        - label: Code readability enhanced

  - type: checkboxes
    id: architecture-requirements
    attributes:
      label: Architecture Requirements
      options:
        - label: Layer boundaries respected (P → A → I, one-way only)
        - label: Command-Query Separation maintained
        - label: No circular dependencies introduced
        - label: Follows existing patterns in codebase

  - type: markdown
    attributes:
      value: |
        ## Implementation Guidance

  - type: textarea
    id: implementation-steps
    attributes:
      label: Implementation Steps
      description: Recommended sequence for refactoring
      placeholder: |
        **Phase 1: Preparation**
        1. Review existing tests and document current behavior
        2. Create comprehensive test suite to verify behavior preservation
        3. Identify all code locations requiring changes

        **Phase 2: Extraction**
        1. Define ProgressCallback protocol in types.py
        2. Create MockProgressCallback in tests/mocks.py
        3. Update tests to use mock (verify behavior unchanged)

        **Phase 3: Integration**
        1. Implement RichProgressCallback in display.py
        2. Modify Scanner to accept callback via constructor
        3. Update CLI to inject RichProgressCallback
        4. Remove direct Rich calls from Scanner

        **Phase 4: Validation**
        1. Run full test suite (all green)
        2. Manual testing with ./vscan
        3. Verify no behavior changes
        4. Check test coverage increased
    validations:
      required: false

  - type: textarea
    id: testing-strategy
    attributes:
      label: Testing Strategy
      description: How to ensure refactoring doesn't break behavior
      placeholder: |
        **Pre-Refactoring:**
        1. Document current behavior with characterization tests
        2. Capture baseline test coverage metrics
        3. Run full test suite to establish green baseline

        **During Refactoring:**
        1. Use MockProgressCallback in all scanner tests
        2. Verify each change doesn't break existing tests
        3. Incremental commits after each green test run

        **Post-Refactoring:**
        1. Run full test suite (pytest tests/)
        2. Verify coverage increased: pytest --cov
        3. Manual smoke testing: ./vscan scan --publisher microsoft
        4. Architecture validation: python tests/test_architecture.py
        5. Security validation: python tests/test_security.py
    validations:
      required: false

  - type: textarea
    id: rollback-plan
    attributes:
      label: Rollback Plan
      description: How to rollback if refactoring causes issues
      placeholder: |
        **Git Workflow:**
        - Use feature branch: `refactor/extract-progress-callback`
        - Commit frequently with clear messages
        - Can revert entire branch if needed

        **Incremental Approach:**
        - Each phase is a separate commit
        - Can rollback to end of previous phase if issues found
        - Keep old implementation alongside new (temporarily) for A/B testing

        **Verification Points:**
        - Phase 1 checkpoint: All tests green, baseline established
        - Phase 2 checkpoint: Mock callback working in tests
        - Phase 3 checkpoint: Real callback working in CLI
        - Phase 4 checkpoint: All tests green, coverage improved
    validations:
      required: false

  - type: textarea
    id: metrics
    attributes:
      label: Success Metrics
      description: How to measure refactoring success
      placeholder: |
        **Before Refactoring:**
        - Test coverage: 72%
        - Cyclomatic complexity: 15 (scan_extension method)
        - Number of mocks in tests: 8 (Rich console mocks)
        - Test brittleness: 5 tests fail when Rich library updates

        **After Refactoring:**
        - Test coverage: ≥85% (target)
        - Cyclomatic complexity: ≤10 (target)
        - Number of mocks in tests: 1 (MockProgressCallback)
        - Test brittleness: 0 tests should fail on Rich updates

        **Validation:**
        - Coverage delta: +13% (72% → 85%)
        - Complexity reduction: -5 points (15 → 10)
        - Mock reduction: -7 mocks (8 → 1)
        - Test reliability: 100% (0 brittle tests)
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: |
        - Related to v3.7 testability roadmap
        - Pattern used in other projects: (links)
        - Similar refactoring in module X (reference)
        - Performance benchmarks before/after
    validations:
      required: false
